//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TigerReader.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Streets_SanDiegoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Streets_SanDiegoEntities object using the connection string found in the 'Streets_SanDiegoEntities' section of the application configuration file.
        /// </summary>
        public Streets_SanDiegoEntities() : base("name=Streets_SanDiegoEntities", "Streets_SanDiegoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Streets_SanDiegoEntities object.
        /// </summary>
        public Streets_SanDiegoEntities(string connectionString) : base(connectionString, "Streets_SanDiegoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Streets_SanDiegoEntities object.
        /// </summary>
        public Streets_SanDiegoEntities(EntityConnection connection) : base(connection, "Streets_SanDiegoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tigerLineId">No Metadata Documentation available.</param>
        /// <param name="rangeId">No Metadata Documentation available.</param>
        /// <param name="first">No Metadata Documentation available.</param>
        /// <param name="last">No Metadata Documentation available.</param>
        public int CreateAddress(Nullable<global::System.Int32> tigerLineId, Nullable<global::System.Int32> rangeId, global::System.String first, global::System.String last)
        {
            ObjectParameter tigerLineIdParameter;
            if (tigerLineId.HasValue)
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", tigerLineId);
            }
            else
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", typeof(global::System.Int32));
            }
    
            ObjectParameter rangeIdParameter;
            if (rangeId.HasValue)
            {
                rangeIdParameter = new ObjectParameter("RangeId", rangeId);
            }
            else
            {
                rangeIdParameter = new ObjectParameter("RangeId", typeof(global::System.Int32));
            }
    
            ObjectParameter firstParameter;
            if (first != null)
            {
                firstParameter = new ObjectParameter("First", first);
            }
            else
            {
                firstParameter = new ObjectParameter("First", typeof(global::System.String));
            }
    
            ObjectParameter lastParameter;
            if (last != null)
            {
                lastParameter = new ObjectParameter("Last", last);
            }
            else
            {
                lastParameter = new ObjectParameter("Last", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("CreateAddress", tigerLineIdParameter, rangeIdParameter, firstParameter, lastParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="placeId">No Metadata Documentation available.</param>
        /// <param name="stateFips">No Metadata Documentation available.</param>
        /// <param name="countyFips">No Metadata Documentation available.</param>
        /// <param name="placeFips">No Metadata Documentation available.</param>
        /// <param name="stateName">No Metadata Documentation available.</param>
        /// <param name="countyName">No Metadata Documentation available.</param>
        /// <param name="placeName">No Metadata Documentation available.</param>
        public int CreatePlace(Nullable<global::System.Int32> placeId, global::System.String stateFips, global::System.String countyFips, global::System.String placeFips, global::System.String stateName, global::System.String countyName, global::System.String placeName)
        {
            ObjectParameter placeIdParameter;
            if (placeId.HasValue)
            {
                placeIdParameter = new ObjectParameter("PlaceId", placeId);
            }
            else
            {
                placeIdParameter = new ObjectParameter("PlaceId", typeof(global::System.Int32));
            }
    
            ObjectParameter stateFipsParameter;
            if (stateFips != null)
            {
                stateFipsParameter = new ObjectParameter("StateFips", stateFips);
            }
            else
            {
                stateFipsParameter = new ObjectParameter("StateFips", typeof(global::System.String));
            }
    
            ObjectParameter countyFipsParameter;
            if (countyFips != null)
            {
                countyFipsParameter = new ObjectParameter("CountyFips", countyFips);
            }
            else
            {
                countyFipsParameter = new ObjectParameter("CountyFips", typeof(global::System.String));
            }
    
            ObjectParameter placeFipsParameter;
            if (placeFips != null)
            {
                placeFipsParameter = new ObjectParameter("PlaceFips", placeFips);
            }
            else
            {
                placeFipsParameter = new ObjectParameter("PlaceFips", typeof(global::System.String));
            }
    
            ObjectParameter stateNameParameter;
            if (stateName != null)
            {
                stateNameParameter = new ObjectParameter("StateName", stateName);
            }
            else
            {
                stateNameParameter = new ObjectParameter("StateName", typeof(global::System.String));
            }
    
            ObjectParameter countyNameParameter;
            if (countyName != null)
            {
                countyNameParameter = new ObjectParameter("CountyName", countyName);
            }
            else
            {
                countyNameParameter = new ObjectParameter("CountyName", typeof(global::System.String));
            }
    
            ObjectParameter placeNameParameter;
            if (placeName != null)
            {
                placeNameParameter = new ObjectParameter("PlaceName", placeName);
            }
            else
            {
                placeNameParameter = new ObjectParameter("PlaceName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("CreatePlace", placeIdParameter, stateFipsParameter, countyFipsParameter, placeFipsParameter, stateNameParameter, countyNameParameter, placeNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tigerLineId">No Metadata Documentation available.</param>
        /// <param name="censusFeatureClassCode">No Metadata Documentation available.</param>
        /// <param name="directionPrefix">No Metadata Documentation available.</param>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="type">No Metadata Documentation available.</param>
        /// <param name="places">No Metadata Documentation available.</param>
        /// <param name="directionSuffix">No Metadata Documentation available.</param>
        public int CreateStreet(Nullable<global::System.Int32> tigerLineId, global::System.String censusFeatureClassCode, global::System.String directionPrefix, global::System.String name, global::System.String type, global::System.String places, global::System.String directionSuffix)
        {
            ObjectParameter tigerLineIdParameter;
            if (tigerLineId.HasValue)
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", tigerLineId);
            }
            else
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", typeof(global::System.Int32));
            }
    
            ObjectParameter censusFeatureClassCodeParameter;
            if (censusFeatureClassCode != null)
            {
                censusFeatureClassCodeParameter = new ObjectParameter("CensusFeatureClassCode", censusFeatureClassCode);
            }
            else
            {
                censusFeatureClassCodeParameter = new ObjectParameter("CensusFeatureClassCode", typeof(global::System.String));
            }
    
            ObjectParameter directionPrefixParameter;
            if (directionPrefix != null)
            {
                directionPrefixParameter = new ObjectParameter("DirectionPrefix", directionPrefix);
            }
            else
            {
                directionPrefixParameter = new ObjectParameter("DirectionPrefix", typeof(global::System.String));
            }
    
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter typeParameter;
            if (type != null)
            {
                typeParameter = new ObjectParameter("Type", type);
            }
            else
            {
                typeParameter = new ObjectParameter("Type", typeof(global::System.String));
            }
    
            ObjectParameter placesParameter;
            if (places != null)
            {
                placesParameter = new ObjectParameter("Places", places);
            }
            else
            {
                placesParameter = new ObjectParameter("Places", typeof(global::System.String));
            }
    
            ObjectParameter directionSuffixParameter;
            if (directionSuffix != null)
            {
                directionSuffixParameter = new ObjectParameter("DirectionSuffix", directionSuffix);
            }
            else
            {
                directionSuffixParameter = new ObjectParameter("DirectionSuffix", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("CreateStreet", tigerLineIdParameter, censusFeatureClassCodeParameter, directionPrefixParameter, nameParameter, typeParameter, placesParameter, directionSuffixParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tigerLineId">No Metadata Documentation available.</param>
        /// <param name="sequence">No Metadata Documentation available.</param>
        /// <param name="latitude">No Metadata Documentation available.</param>
        /// <param name="longitude">No Metadata Documentation available.</param>
        public int CreateStreetSegment(Nullable<global::System.Int32> tigerLineId, Nullable<global::System.Int32> sequence, Nullable<global::System.Double> latitude, Nullable<global::System.Double> longitude)
        {
            ObjectParameter tigerLineIdParameter;
            if (tigerLineId.HasValue)
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", tigerLineId);
            }
            else
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", typeof(global::System.Int32));
            }
    
            ObjectParameter sequenceParameter;
            if (sequence.HasValue)
            {
                sequenceParameter = new ObjectParameter("Sequence", sequence);
            }
            else
            {
                sequenceParameter = new ObjectParameter("Sequence", typeof(global::System.Int32));
            }
    
            ObjectParameter latitudeParameter;
            if (latitude.HasValue)
            {
                latitudeParameter = new ObjectParameter("Latitude", latitude);
            }
            else
            {
                latitudeParameter = new ObjectParameter("Latitude", typeof(global::System.Double));
            }
    
            ObjectParameter longitudeParameter;
            if (longitude.HasValue)
            {
                longitudeParameter = new ObjectParameter("Longitude", longitude);
            }
            else
            {
                longitudeParameter = new ObjectParameter("Longitude", typeof(global::System.Double));
            }
    
            return base.ExecuteFunction("CreateStreetSegment", tigerLineIdParameter, sequenceParameter, latitudeParameter, longitudeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetAllStreetNames_Result> GetAllStreetNames()
        {
            return base.ExecuteFunction<GetAllStreetNames_Result>("GetAllStreetNames");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="number">No Metadata Documentation available.</param>
        /// <param name="place_id">No Metadata Documentation available.</param>
        /// <param name="street">No Metadata Documentation available.</param>
        public ObjectResult<GetStreetByAddress_Result> GetStreetByAddress(Nullable<global::System.Int32> number, Nullable<global::System.Int32> place_id, global::System.String street)
        {
            ObjectParameter numberParameter;
            if (number.HasValue)
            {
                numberParameter = new ObjectParameter("number", number);
            }
            else
            {
                numberParameter = new ObjectParameter("number", typeof(global::System.Int32));
            }
    
            ObjectParameter place_idParameter;
            if (place_id.HasValue)
            {
                place_idParameter = new ObjectParameter("place_id", place_id);
            }
            else
            {
                place_idParameter = new ObjectParameter("place_id", typeof(global::System.Int32));
            }
    
            ObjectParameter streetParameter;
            if (street != null)
            {
                streetParameter = new ObjectParameter("street", street);
            }
            else
            {
                streetParameter = new ObjectParameter("street", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetStreetByAddress_Result>("GetStreetByAddress", numberParameter, place_idParameter, streetParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tigerLineId">No Metadata Documentation available.</param>
        public ObjectResult<GetStreetNameById_Result> GetStreetNameById(Nullable<global::System.Int32> tigerLineId)
        {
            ObjectParameter tigerLineIdParameter;
            if (tigerLineId.HasValue)
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", tigerLineId);
            }
            else
            {
                tigerLineIdParameter = new ObjectParameter("TigerLineId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetStreetNameById_Result>("GetStreetNameById", tigerLineIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tigerLineIdList">No Metadata Documentation available.</param>
        public ObjectResult<GetStreetNamesByIdList_Result> GetStreetNamesByIdList(global::System.String tigerLineIdList)
        {
            ObjectParameter tigerLineIdListParameter;
            if (tigerLineIdList != null)
            {
                tigerLineIdListParameter = new ObjectParameter("TigerLineIdList", tigerLineIdList);
            }
            else
            {
                tigerLineIdListParameter = new ObjectParameter("TigerLineIdList", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetStreetNamesByIdList_Result>("GetStreetNamesByIdList", tigerLineIdListParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cityName">No Metadata Documentation available.</param>
        /// <param name="stateName">No Metadata Documentation available.</param>
        public ObjectResult<GetPlaceByCityAndState_Result> GetPlaceByCityAndState(global::System.String cityName, global::System.String stateName)
        {
            ObjectParameter cityNameParameter;
            if (cityName != null)
            {
                cityNameParameter = new ObjectParameter("CityName", cityName);
            }
            else
            {
                cityNameParameter = new ObjectParameter("CityName", typeof(global::System.String));
            }
    
            ObjectParameter stateNameParameter;
            if (stateName != null)
            {
                stateNameParameter = new ObjectParameter("StateName", stateName);
            }
            else
            {
                stateNameParameter = new ObjectParameter("StateName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetPlaceByCityAndState_Result>("GetPlaceByCityAndState", cityNameParameter, stateNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="stateName">No Metadata Documentation available.</param>
        public ObjectResult<GetPlacesByState_Result> GetPlacesByState(global::System.String stateName)
        {
            ObjectParameter stateNameParameter;
            if (stateName != null)
            {
                stateNameParameter = new ObjectParameter("StateName", stateName);
            }
            else
            {
                stateNameParameter = new ObjectParameter("StateName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetPlacesByState_Result>("GetPlacesByState", stateNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tLID">No Metadata Documentation available.</param>
        public ObjectResult<GetStreetSegmentsByTLIDOrdered_Result> GetStreetSegmentsByTLIDOrdered(Nullable<global::System.Int32> tLID)
        {
            ObjectParameter tLIDParameter;
            if (tLID.HasValue)
            {
                tLIDParameter = new ObjectParameter("TLID", tLID);
            }
            else
            {
                tLIDParameter = new ObjectParameter("TLID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetStreetSegmentsByTLIDOrdered_Result>("GetStreetSegmentsByTLIDOrdered", tLIDParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetAllStreetNames_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetAllStreetNames_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetAllStreetNames_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tigerLineId">Initial value of the TigerLineId property.</param>
        /// <param name="placeId">Initial value of the PlaceId property.</param>
        /// <param name="censusFeatureClassCode">Initial value of the CensusFeatureClassCode property.</param>
        /// <param name="directionPrefix">Initial value of the DirectionPrefix property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="directionSuffix">Initial value of the DirectionSuffix property.</param>
        public static GetAllStreetNames_Result CreateGetAllStreetNames_Result(global::System.Int32 id, global::System.Int32 tigerLineId, global::System.Int32 placeId, global::System.String censusFeatureClassCode, global::System.String directionPrefix, global::System.String name, global::System.String type, global::System.String directionSuffix)
        {
            GetAllStreetNames_Result getAllStreetNames_Result = new GetAllStreetNames_Result();
            getAllStreetNames_Result.Id = id;
            getAllStreetNames_Result.TigerLineId = tigerLineId;
            getAllStreetNames_Result.PlaceId = placeId;
            getAllStreetNames_Result.CensusFeatureClassCode = censusFeatureClassCode;
            getAllStreetNames_Result.DirectionPrefix = directionPrefix;
            getAllStreetNames_Result.Name = name;
            getAllStreetNames_Result.Type = type;
            getAllStreetNames_Result.DirectionSuffix = directionSuffix;
            return getAllStreetNames_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TigerLineId
        {
            get
            {
                return _TigerLineId;
            }
            set
            {
                OnTigerLineIdChanging(value);
                ReportPropertyChanging("TigerLineId");
                _TigerLineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TigerLineId");
                OnTigerLineIdChanged();
            }
        }
        private global::System.Int32 _TigerLineId;
        partial void OnTigerLineIdChanging(global::System.Int32 value);
        partial void OnTigerLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlaceId
        {
            get
            {
                return _PlaceId;
            }
            set
            {
                OnPlaceIdChanging(value);
                ReportPropertyChanging("PlaceId");
                _PlaceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlaceId");
                OnPlaceIdChanged();
            }
        }
        private global::System.Int32 _PlaceId;
        partial void OnPlaceIdChanging(global::System.Int32 value);
        partial void OnPlaceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CensusFeatureClassCode
        {
            get
            {
                return _CensusFeatureClassCode;
            }
            set
            {
                OnCensusFeatureClassCodeChanging(value);
                ReportPropertyChanging("CensusFeatureClassCode");
                _CensusFeatureClassCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CensusFeatureClassCode");
                OnCensusFeatureClassCodeChanged();
            }
        }
        private global::System.String _CensusFeatureClassCode;
        partial void OnCensusFeatureClassCodeChanging(global::System.String value);
        partial void OnCensusFeatureClassCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionPrefix
        {
            get
            {
                return _DirectionPrefix;
            }
            set
            {
                OnDirectionPrefixChanging(value);
                ReportPropertyChanging("DirectionPrefix");
                _DirectionPrefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionPrefix");
                OnDirectionPrefixChanged();
            }
        }
        private global::System.String _DirectionPrefix;
        partial void OnDirectionPrefixChanging(global::System.String value);
        partial void OnDirectionPrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionSuffix
        {
            get
            {
                return _DirectionSuffix;
            }
            set
            {
                OnDirectionSuffixChanging(value);
                ReportPropertyChanging("DirectionSuffix");
                _DirectionSuffix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionSuffix");
                OnDirectionSuffixChanged();
            }
        }
        private global::System.String _DirectionSuffix;
        partial void OnDirectionSuffixChanging(global::System.String value);
        partial void OnDirectionSuffixChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetPlaceByCityAndState_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetPlaceByCityAndState_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetPlaceByCityAndState_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="stateCode">Initial value of the StateCode property.</param>
        /// <param name="countyCode">Initial value of the CountyCode property.</param>
        /// <param name="placeCode">Initial value of the PlaceCode property.</param>
        /// <param name="stateName">Initial value of the StateName property.</param>
        /// <param name="countyName">Initial value of the CountyName property.</param>
        /// <param name="placeName">Initial value of the PlaceName property.</param>
        public static GetPlaceByCityAndState_Result CreateGetPlaceByCityAndState_Result(global::System.Int32 id, global::System.String stateCode, global::System.String countyCode, global::System.String placeCode, global::System.String stateName, global::System.String countyName, global::System.String placeName)
        {
            GetPlaceByCityAndState_Result getPlaceByCityAndState_Result = new GetPlaceByCityAndState_Result();
            getPlaceByCityAndState_Result.Id = id;
            getPlaceByCityAndState_Result.StateCode = stateCode;
            getPlaceByCityAndState_Result.CountyCode = countyCode;
            getPlaceByCityAndState_Result.PlaceCode = placeCode;
            getPlaceByCityAndState_Result.StateName = stateName;
            getPlaceByCityAndState_Result.CountyName = countyName;
            getPlaceByCityAndState_Result.PlaceName = placeName;
            return getPlaceByCityAndState_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountyCode
        {
            get
            {
                return _CountyCode;
            }
            set
            {
                OnCountyCodeChanging(value);
                ReportPropertyChanging("CountyCode");
                _CountyCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CountyCode");
                OnCountyCodeChanged();
            }
        }
        private global::System.String _CountyCode;
        partial void OnCountyCodeChanging(global::System.String value);
        partial void OnCountyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlaceCode
        {
            get
            {
                return _PlaceCode;
            }
            set
            {
                OnPlaceCodeChanging(value);
                ReportPropertyChanging("PlaceCode");
                _PlaceCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlaceCode");
                OnPlaceCodeChanged();
            }
        }
        private global::System.String _PlaceCode;
        partial void OnPlaceCodeChanging(global::System.String value);
        partial void OnPlaceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateName
        {
            get
            {
                return _StateName;
            }
            set
            {
                OnStateNameChanging(value);
                ReportPropertyChanging("StateName");
                _StateName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateName");
                OnStateNameChanged();
            }
        }
        private global::System.String _StateName;
        partial void OnStateNameChanging(global::System.String value);
        partial void OnStateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountyName
        {
            get
            {
                return _CountyName;
            }
            set
            {
                OnCountyNameChanging(value);
                ReportPropertyChanging("CountyName");
                _CountyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CountyName");
                OnCountyNameChanged();
            }
        }
        private global::System.String _CountyName;
        partial void OnCountyNameChanging(global::System.String value);
        partial void OnCountyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlaceName
        {
            get
            {
                return _PlaceName;
            }
            set
            {
                OnPlaceNameChanging(value);
                ReportPropertyChanging("PlaceName");
                _PlaceName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlaceName");
                OnPlaceNameChanged();
            }
        }
        private global::System.String _PlaceName;
        partial void OnPlaceNameChanging(global::System.String value);
        partial void OnPlaceNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetPlacesByState_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetPlacesByState_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetPlacesByState_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="stateCode">Initial value of the StateCode property.</param>
        /// <param name="countyCode">Initial value of the CountyCode property.</param>
        /// <param name="placeCode">Initial value of the PlaceCode property.</param>
        /// <param name="stateName">Initial value of the StateName property.</param>
        /// <param name="countyName">Initial value of the CountyName property.</param>
        /// <param name="placeName">Initial value of the PlaceName property.</param>
        public static GetPlacesByState_Result CreateGetPlacesByState_Result(global::System.Int32 id, global::System.String stateCode, global::System.String countyCode, global::System.String placeCode, global::System.String stateName, global::System.String countyName, global::System.String placeName)
        {
            GetPlacesByState_Result getPlacesByState_Result = new GetPlacesByState_Result();
            getPlacesByState_Result.Id = id;
            getPlacesByState_Result.StateCode = stateCode;
            getPlacesByState_Result.CountyCode = countyCode;
            getPlacesByState_Result.PlaceCode = placeCode;
            getPlacesByState_Result.StateName = stateName;
            getPlacesByState_Result.CountyName = countyName;
            getPlacesByState_Result.PlaceName = placeName;
            return getPlacesByState_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountyCode
        {
            get
            {
                return _CountyCode;
            }
            set
            {
                OnCountyCodeChanging(value);
                ReportPropertyChanging("CountyCode");
                _CountyCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CountyCode");
                OnCountyCodeChanged();
            }
        }
        private global::System.String _CountyCode;
        partial void OnCountyCodeChanging(global::System.String value);
        partial void OnCountyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlaceCode
        {
            get
            {
                return _PlaceCode;
            }
            set
            {
                OnPlaceCodeChanging(value);
                ReportPropertyChanging("PlaceCode");
                _PlaceCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlaceCode");
                OnPlaceCodeChanged();
            }
        }
        private global::System.String _PlaceCode;
        partial void OnPlaceCodeChanging(global::System.String value);
        partial void OnPlaceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateName
        {
            get
            {
                return _StateName;
            }
            set
            {
                OnStateNameChanging(value);
                ReportPropertyChanging("StateName");
                _StateName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateName");
                OnStateNameChanged();
            }
        }
        private global::System.String _StateName;
        partial void OnStateNameChanging(global::System.String value);
        partial void OnStateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountyName
        {
            get
            {
                return _CountyName;
            }
            set
            {
                OnCountyNameChanging(value);
                ReportPropertyChanging("CountyName");
                _CountyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CountyName");
                OnCountyNameChanged();
            }
        }
        private global::System.String _CountyName;
        partial void OnCountyNameChanging(global::System.String value);
        partial void OnCountyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlaceName
        {
            get
            {
                return _PlaceName;
            }
            set
            {
                OnPlaceNameChanging(value);
                ReportPropertyChanging("PlaceName");
                _PlaceName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlaceName");
                OnPlaceNameChanged();
            }
        }
        private global::System.String _PlaceName;
        partial void OnPlaceNameChanging(global::System.String value);
        partial void OnPlaceNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetStreetByAddress_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetStreetByAddress_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetStreetByAddress_Result object.
        /// </summary>
        /// <param name="tigerLineId">Initial value of the TigerLineId property.</param>
        /// <param name="first">Initial value of the First property.</param>
        /// <param name="last">Initial value of the Last property.</param>
        public static GetStreetByAddress_Result CreateGetStreetByAddress_Result(global::System.Int32 tigerLineId, global::System.String first, global::System.String last)
        {
            GetStreetByAddress_Result getStreetByAddress_Result = new GetStreetByAddress_Result();
            getStreetByAddress_Result.TigerLineId = tigerLineId;
            getStreetByAddress_Result.First = first;
            getStreetByAddress_Result.Last = last;
            return getStreetByAddress_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TigerLineId
        {
            get
            {
                return _TigerLineId;
            }
            set
            {
                OnTigerLineIdChanging(value);
                ReportPropertyChanging("TigerLineId");
                _TigerLineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TigerLineId");
                OnTigerLineIdChanged();
            }
        }
        private global::System.Int32 _TigerLineId;
        partial void OnTigerLineIdChanging(global::System.Int32 value);
        partial void OnTigerLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First
        {
            get
            {
                return _First;
            }
            set
            {
                OnFirstChanging(value);
                ReportPropertyChanging("First");
                _First = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First");
                OnFirstChanged();
            }
        }
        private global::System.String _First;
        partial void OnFirstChanging(global::System.String value);
        partial void OnFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last
        {
            get
            {
                return _Last;
            }
            set
            {
                OnLastChanging(value);
                ReportPropertyChanging("Last");
                _Last = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last");
                OnLastChanged();
            }
        }
        private global::System.String _Last;
        partial void OnLastChanging(global::System.String value);
        partial void OnLastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Diff
        {
            get
            {
                return _Diff;
            }
            set
            {
                OnDiffChanging(value);
                ReportPropertyChanging("Diff");
                _Diff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diff");
                OnDiffChanged();
            }
        }
        private Nullable<global::System.Int32> _Diff;
        partial void OnDiffChanging(Nullable<global::System.Int32> value);
        partial void OnDiffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullAddress
        {
            get
            {
                return _FullAddress;
            }
            set
            {
                OnFullAddressChanging(value);
                ReportPropertyChanging("FullAddress");
                _FullAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullAddress");
                OnFullAddressChanged();
            }
        }
        private global::System.String _FullAddress;
        partial void OnFullAddressChanging(global::System.String value);
        partial void OnFullAddressChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetStreetNameById_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetStreetNameById_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetStreetNameById_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tigerLineId">Initial value of the TigerLineId property.</param>
        /// <param name="placeId">Initial value of the PlaceId property.</param>
        /// <param name="censusFeatureClassCode">Initial value of the CensusFeatureClassCode property.</param>
        /// <param name="directionPrefix">Initial value of the DirectionPrefix property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="directionSuffix">Initial value of the DirectionSuffix property.</param>
        public static GetStreetNameById_Result CreateGetStreetNameById_Result(global::System.Int32 id, global::System.Int32 tigerLineId, global::System.Int32 placeId, global::System.String censusFeatureClassCode, global::System.String directionPrefix, global::System.String name, global::System.String type, global::System.String directionSuffix)
        {
            GetStreetNameById_Result getStreetNameById_Result = new GetStreetNameById_Result();
            getStreetNameById_Result.Id = id;
            getStreetNameById_Result.TigerLineId = tigerLineId;
            getStreetNameById_Result.PlaceId = placeId;
            getStreetNameById_Result.CensusFeatureClassCode = censusFeatureClassCode;
            getStreetNameById_Result.DirectionPrefix = directionPrefix;
            getStreetNameById_Result.Name = name;
            getStreetNameById_Result.Type = type;
            getStreetNameById_Result.DirectionSuffix = directionSuffix;
            return getStreetNameById_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TigerLineId
        {
            get
            {
                return _TigerLineId;
            }
            set
            {
                OnTigerLineIdChanging(value);
                ReportPropertyChanging("TigerLineId");
                _TigerLineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TigerLineId");
                OnTigerLineIdChanged();
            }
        }
        private global::System.Int32 _TigerLineId;
        partial void OnTigerLineIdChanging(global::System.Int32 value);
        partial void OnTigerLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlaceId
        {
            get
            {
                return _PlaceId;
            }
            set
            {
                OnPlaceIdChanging(value);
                ReportPropertyChanging("PlaceId");
                _PlaceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlaceId");
                OnPlaceIdChanged();
            }
        }
        private global::System.Int32 _PlaceId;
        partial void OnPlaceIdChanging(global::System.Int32 value);
        partial void OnPlaceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CensusFeatureClassCode
        {
            get
            {
                return _CensusFeatureClassCode;
            }
            set
            {
                OnCensusFeatureClassCodeChanging(value);
                ReportPropertyChanging("CensusFeatureClassCode");
                _CensusFeatureClassCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CensusFeatureClassCode");
                OnCensusFeatureClassCodeChanged();
            }
        }
        private global::System.String _CensusFeatureClassCode;
        partial void OnCensusFeatureClassCodeChanging(global::System.String value);
        partial void OnCensusFeatureClassCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionPrefix
        {
            get
            {
                return _DirectionPrefix;
            }
            set
            {
                OnDirectionPrefixChanging(value);
                ReportPropertyChanging("DirectionPrefix");
                _DirectionPrefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionPrefix");
                OnDirectionPrefixChanged();
            }
        }
        private global::System.String _DirectionPrefix;
        partial void OnDirectionPrefixChanging(global::System.String value);
        partial void OnDirectionPrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionSuffix
        {
            get
            {
                return _DirectionSuffix;
            }
            set
            {
                OnDirectionSuffixChanging(value);
                ReportPropertyChanging("DirectionSuffix");
                _DirectionSuffix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionSuffix");
                OnDirectionSuffixChanged();
            }
        }
        private global::System.String _DirectionSuffix;
        partial void OnDirectionSuffixChanging(global::System.String value);
        partial void OnDirectionSuffixChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetStreetNamesByIdList_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetStreetNamesByIdList_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetStreetNamesByIdList_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tigerLineId">Initial value of the TigerLineId property.</param>
        /// <param name="placeId">Initial value of the PlaceId property.</param>
        /// <param name="censusFeatureClassCode">Initial value of the CensusFeatureClassCode property.</param>
        /// <param name="directionPrefix">Initial value of the DirectionPrefix property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="directionSuffix">Initial value of the DirectionSuffix property.</param>
        public static GetStreetNamesByIdList_Result CreateGetStreetNamesByIdList_Result(global::System.Int32 id, global::System.Int32 tigerLineId, global::System.Int32 placeId, global::System.String censusFeatureClassCode, global::System.String directionPrefix, global::System.String name, global::System.String type, global::System.String directionSuffix)
        {
            GetStreetNamesByIdList_Result getStreetNamesByIdList_Result = new GetStreetNamesByIdList_Result();
            getStreetNamesByIdList_Result.Id = id;
            getStreetNamesByIdList_Result.TigerLineId = tigerLineId;
            getStreetNamesByIdList_Result.PlaceId = placeId;
            getStreetNamesByIdList_Result.CensusFeatureClassCode = censusFeatureClassCode;
            getStreetNamesByIdList_Result.DirectionPrefix = directionPrefix;
            getStreetNamesByIdList_Result.Name = name;
            getStreetNamesByIdList_Result.Type = type;
            getStreetNamesByIdList_Result.DirectionSuffix = directionSuffix;
            return getStreetNamesByIdList_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TigerLineId
        {
            get
            {
                return _TigerLineId;
            }
            set
            {
                OnTigerLineIdChanging(value);
                ReportPropertyChanging("TigerLineId");
                _TigerLineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TigerLineId");
                OnTigerLineIdChanged();
            }
        }
        private global::System.Int32 _TigerLineId;
        partial void OnTigerLineIdChanging(global::System.Int32 value);
        partial void OnTigerLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlaceId
        {
            get
            {
                return _PlaceId;
            }
            set
            {
                OnPlaceIdChanging(value);
                ReportPropertyChanging("PlaceId");
                _PlaceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlaceId");
                OnPlaceIdChanged();
            }
        }
        private global::System.Int32 _PlaceId;
        partial void OnPlaceIdChanging(global::System.Int32 value);
        partial void OnPlaceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CensusFeatureClassCode
        {
            get
            {
                return _CensusFeatureClassCode;
            }
            set
            {
                OnCensusFeatureClassCodeChanging(value);
                ReportPropertyChanging("CensusFeatureClassCode");
                _CensusFeatureClassCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CensusFeatureClassCode");
                OnCensusFeatureClassCodeChanged();
            }
        }
        private global::System.String _CensusFeatureClassCode;
        partial void OnCensusFeatureClassCodeChanging(global::System.String value);
        partial void OnCensusFeatureClassCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionPrefix
        {
            get
            {
                return _DirectionPrefix;
            }
            set
            {
                OnDirectionPrefixChanging(value);
                ReportPropertyChanging("DirectionPrefix");
                _DirectionPrefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionPrefix");
                OnDirectionPrefixChanged();
            }
        }
        private global::System.String _DirectionPrefix;
        partial void OnDirectionPrefixChanging(global::System.String value);
        partial void OnDirectionPrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectionSuffix
        {
            get
            {
                return _DirectionSuffix;
            }
            set
            {
                OnDirectionSuffixChanging(value);
                ReportPropertyChanging("DirectionSuffix");
                _DirectionSuffix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectionSuffix");
                OnDirectionSuffixChanged();
            }
        }
        private global::System.String _DirectionSuffix;
        partial void OnDirectionSuffixChanging(global::System.String value);
        partial void OnDirectionSuffixChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Streets_SanDiegoModel", Name="GetStreetSegmentsByTLIDOrdered_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetStreetSegmentsByTLIDOrdered_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetStreetSegmentsByTLIDOrdered_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tigerLineId">Initial value of the TigerLineId property.</param>
        /// <param name="sequence">Initial value of the Sequence property.</param>
        public static GetStreetSegmentsByTLIDOrdered_Result CreateGetStreetSegmentsByTLIDOrdered_Result(global::System.Int32 id, global::System.Int32 tigerLineId, global::System.Int32 sequence)
        {
            GetStreetSegmentsByTLIDOrdered_Result getStreetSegmentsByTLIDOrdered_Result = new GetStreetSegmentsByTLIDOrdered_Result();
            getStreetSegmentsByTLIDOrdered_Result.Id = id;
            getStreetSegmentsByTLIDOrdered_Result.TigerLineId = tigerLineId;
            getStreetSegmentsByTLIDOrdered_Result.Sequence = sequence;
            return getStreetSegmentsByTLIDOrdered_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TigerLineId
        {
            get
            {
                return _TigerLineId;
            }
            set
            {
                OnTigerLineIdChanging(value);
                ReportPropertyChanging("TigerLineId");
                _TigerLineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TigerLineId");
                OnTigerLineIdChanged();
            }
        }
        private global::System.Int32 _TigerLineId;
        partial void OnTigerLineIdChanging(global::System.Int32 value);
        partial void OnTigerLineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private global::System.Int32 _Sequence;
        partial void OnSequenceChanging(global::System.Int32 value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();

        #endregion
    }

    #endregion
    
}
